/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserAuth } from "./UserAuth";
import { UserAuthCountArgs } from "./UserAuthCountArgs";
import { UserAuthFindManyArgs } from "./UserAuthFindManyArgs";
import { UserAuthFindUniqueArgs } from "./UserAuthFindUniqueArgs";
import { CreateUserAuthArgs } from "./CreateUserAuthArgs";
import { UpdateUserAuthArgs } from "./UpdateUserAuthArgs";
import { DeleteUserAuthArgs } from "./DeleteUserAuthArgs";
import { UserAuthService } from "../userAuth.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserAuth)
export class UserAuthResolverBase {
  constructor(
    protected readonly service: UserAuthService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserAuth",
    action: "read",
    possession: "any",
  })
  async _userAuthsMeta(
    @graphql.Args() args: UserAuthCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserAuth])
  @nestAccessControl.UseRoles({
    resource: "UserAuth",
    action: "read",
    possession: "any",
  })
  async userAuths(
    @graphql.Args() args: UserAuthFindManyArgs
  ): Promise<UserAuth[]> {
    return this.service.userAuths(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserAuth, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserAuth",
    action: "read",
    possession: "own",
  })
  async userAuth(
    @graphql.Args() args: UserAuthFindUniqueArgs
  ): Promise<UserAuth | null> {
    const result = await this.service.userAuth(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserAuth)
  @nestAccessControl.UseRoles({
    resource: "UserAuth",
    action: "create",
    possession: "any",
  })
  async createUserAuth(
    @graphql.Args() args: CreateUserAuthArgs
  ): Promise<UserAuth> {
    return await this.service.createUserAuth({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserAuth)
  @nestAccessControl.UseRoles({
    resource: "UserAuth",
    action: "update",
    possession: "any",
  })
  async updateUserAuth(
    @graphql.Args() args: UpdateUserAuthArgs
  ): Promise<UserAuth | null> {
    try {
      return await this.service.updateUserAuth({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserAuth)
  @nestAccessControl.UseRoles({
    resource: "UserAuth",
    action: "delete",
    possession: "any",
  })
  async deleteUserAuth(
    @graphql.Args() args: DeleteUserAuthArgs
  ): Promise<UserAuth | null> {
    try {
      return await this.service.deleteUserAuth(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
