# Introduction:
#
# This workflow is responsible for both creating and pushing the container image of the generated service to
# Amazon Elastic Container Registry (ECR), aswell as rendering and deploying an task definition to an Amazon
# Elastic Container Service (ECS) cluster. Lastly the execution of a task definition requires as IAM role which
# can be consumed.

name: study-forge-backend-deploy-to-aws-ecs
concurrency: ${{ github.ref }}

on:
  workflow_dispatch: {}
  pull_request:
    types: [closed]

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: repository-name
  ECS_SERVICE: study-forge-backend
  ECS_CLUSTER: development-cluster
  ECS_TASK_DEFINITION: .github/workflows/configuration/cd-study-forge-backend-aws-ecs.json
  CONTAINER_NAME: study-forge-backend

jobs:
  package:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: login to amazon ecr
        id: registry
        uses: aws-actions/amazon-ecr-login@v2

      - name: build, tag and push image
        id: image
        env:
          ECR_REGISTRY: ${{ steps.registry.outputs.registry }}
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG apps/study-forge-backend-server
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # https://github.com/aws-actions/amazon-ecs-render-task-definition
      - name: render amazon ecs task definition
        id: task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.image.outputs.image }}

      # https://github.com/aws-actions/amazon-ecs-deploy-task-definition
      - name: deploy amazon ecs task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-definition.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false
